# SPDX-FileCopyrightText: Copyright (c) 2022-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: modify-readme

'on':
  workflow_dispatch:
  push:
    paths:
      - "src/eoc.js"
concurrency:
  group: modifyreadme-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Use Node
        uses: actions/setup-node@v6
        with:
          node-version: "18.x"
          check-latest: false
      - name: Clean install
        run: npm ci -g
      - name: Run modify_read script
        run: |-
          bash scripts/modify_readme.sh
